privileges:
  masters:
    Item: item
    Service: service
    Category: category
    Warehouse: warehouse
    Supplier: supplier
    PLU: plu
    Salesman: salesman
    Customer: customer
    Currency: currency
    'Exchange Rate': exchange_rate
    'Transaction Type': transaction_type
    'Price List': price_list
    'Assembly Formula': assy_formulae
    User: user
    Role: role
    Company: company
  transactions:
    'Beginning Balance': beginning_balance
    'General Transaction': general_transaction
    'Material Request': material_request
    'Quotation Request': quotation_request
    'Purchase Order': purchase_order
    'Item Receive': item_receive
    'Purchase Return': purchase_return
    Quotation: quotation
    'Sales Order': sales_order
    Assembling: trans_assemblies
    Disassembling: trans_diassemblies
    'Work Order': work_orders
    'Credit / Debit Note': credit_debit_note
    'Purchase Invoice': invoice
    'Delivery Order': delivery_order
    'Sales Invoice': sales_invoice
    'Sales Return': sales_return
    'Direct Sale': direct_sale
