privileges:
  - item
  - category
  - warehouse
  - supplier
  - plu
  - salesman
  - customer
  - currency
  - exchange_rate
  - transaction_type
  - price_list
  - assy_formulae
  - user
  - role
  - company
